export const LOAD_COMPETITION_DATA = 'LOAD_COMPETITION_DATA';
export const LOAD_COMPETITION_NEWS_DATA_SUCCESS = 'LOAD_COMPETITION_NEWS_DATA_SUCCESS';
export const LOAD_COMPETITION_DATA_SUCCESS = 'LOAD_COMPETITION_DATA_SUCCESS';

export const LOAD_REVENUE_DATA_SUCCESS = 'LOAD_REVENUE_DATA_SUCCESS';
export const LOAD_AGILITY_DATA_SUCCESS = 'LOAD_AGILITY_DATA_SUCCESS';
export const INVALIDATE_AGILITY_DATA = 'INVALIDATE_AGILITY_DATA';

export const LOAD_AIVA_FUNNEL_DATA_SUCCESS = 'LOAD_AIVA_FUNNEL_DATA_SUCCESS';
export const LOAD_CHAT_FUNNEL_DATA_SUCCESS = 'LOAD_CHAT_FUNNEL_DATA_SUCCESS';

export const LOAD_INCIDENTS_DATA_SUCCESS = 'LOAD_INCIDENTS_DATA_SUCCESS';
export const INVALIDATE_INCIDENTS_DATA = 'INVALIDATE_INCIDENTS_DATA';

export const LOAD_AVAILABILITY_DATA_SUCCESS = 'LOAD_AVAILABILITY_DATA_SUCCESS';

export const LOAD_PERSONWEEKS_DATA_SUCCESS = 'LOAD_PERSONWEEKS_DATA_SUCCESS';
export const INVALIDATE_PERSONWEEKS_DATA = 'INVALIDATE_PERSONWEEKS_DATA';

export const UPDATE_PERSONWEEKS_DATA_SUCCESS = 'UPDATE_PERSONWEEKS_DATA_SUCCESS';
export const INVALIDATE_PERSONWEEKS_POST = 'INVALIDATE_PERSONWEEKS_POST';

export const LOAD_INCIDENTS_HEATMAP_DATA_SUCCESS = 'LOAD_INCIDENTS_HEATMAP_DATA_SUCCESS';
export const LOAD_INCIDENTS_DAE_DAILY_DATA_SUCCESS = 'LOAD_INCIDENTS_DAE_DAILY_DATA_SUCCESS';
export const LOAD_INCIDENTS_DAE_WEEKLY_DATA_SUCCESS = 'LOAD_INCIDENTS_DAE_WEEKLY_DATA_SUCCESS';
export const LOAD_INCIDENTS_DAE_MONTHLY_DATA_SUCCESS = 'LOAD_INCIDENTS_DAE_MONTHLY_DATA_SUCCESS';
export const LOAD_INCIDENTS_DAE_WEEKLY_DRILLDOWN_DATA_SUCCESS = 'LOAD_INCIDENTS_DAE_WEEKLY_DRILLDOWN_DATA_SUCCESS';
export const LOAD_INCIDENTS_DAE_MONTHLY_DRILLDOWN_DATA_SUCCESS = 'LOAD_INCIDENTS_DAE_MONTHLY_DRILLDOWN_DATA_SUCCESS';
export const INCIDENTS_DAE_DAILY_DATA_INVALID = 'INCIDENTS_DAE_DAILY_DATA_INVALID';
export const INCIDENTS_DAE_WEEKLY_DATA_INVALID = 'INCIDENTS_DAE_WEEKLY_DATA_INVALID';
export const INCIDENTS_DAE_MONTHLY_DATA_INVALID = 'INCIDENTS_DAE_MONTHLY_DATA_INVALID';
export const INCIDENTS_DAE_WEEKLY_DRILLDOWN_DATA_INVALID = 'INCIDENTS_DAE_WEEKLY_DRILLDOWN_DATA_INVALID';
export const INCIDENTS_DAE_MONTHLY_DRILLDOWN_DATA_INVALID = 'INCIDENTS_DAE_MONTHLY_DRILLDOWN_DATA_INVALID';